### ISSUE TITLE
SBS conversion to Beast

### ISSUE THREAD

**Issue by ivandiazperez** [denzen84/beastblackbox#1]
Good afternoon,
in my case, having a bunch of captured data (over a year) in SBS format, would it be possible to transform it into beast format data?

Regards,
Iván D.

**Comment by denzen84** [comment]
It's not a good idea, because SBS data can't be exactly converted to BEAST again. I don't know converters for non-real time SBS data. You can use modesmixer2 to convert SBS to BEAST in real time and save BEAST traffic. But the best case is to save direct BEAST traffic.
