### ISSUE TITLE
passing --lat and --lon

### ISSUE THREAD

**Issue by Rabijns** [denzen84/beastblackbox#2]
The recordings I have in beast format contain DF18 messages from vehicles.
To correctly decode the position in these messages with dump1090, one has to set the --lat and --lon options.
Is there a way to use --lat and --lon with beastblackbox?

**Comment by denzen84** [comment]
No, there is no way.  My new idea is to integrate `beastblackbox` with `dump1090-fa`. And options --lat and --lon will be available.

**Comment by Rabijns** [comment]
good to know. It would be very useful for me if I could use the --lat and --lon options.
Do you have any timeframe in mind for the change to dump1090-fa?

**Comment by denzen84** [comment]
I think next month will be release...

**Comment by denzen84** [comment]
I release build-in functionality of `beastblackbox` into dump1090-fa and made [pull request](https://github.com/flightaware/dump1090/pull/35).
You can clone and compile from [my repository of dump1090-fa](https://github.com/denzen84/dump1090) this version.
